# Generated by Django 3.1.7 on 2022-03-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
    ]
